### ISSUE TITLE
Error when using native SCSS compiler

### ISSUE THREAD

**Issue by vazamb** [brianmaierjr/long-haul#17]
I get an error when I try to use the native Jekyll SCSS compiler

````
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    File to import not found or unreadable: compass. Load path: /Users/valentin/development/webdev/blog/assets/_scss on line 2
````

When I comment out the 2 external files compass and normalize I get this error

````
 Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    Undefined mixin 'transition'. on line 20

````

This is the entry I added to the _config.yml

````
sass:
  sass_dir: scss
````

I have moved the style.css and the ie.scss into the css folder and added frontmatter.
I have also gem installed normalize-scss and susy

EDIT: I am only trying to use the native compiler because I can't seem to get compass working. The command is "undefined", even though I have installed ti normalize-scss gem

**Comment by brianmaierjr** [comment]
Hey @vazamb,

This theme was designed to use Compass but if you want to convert it to use Jekyll compiling then go for it! Unfortunately I have no experience with that and I do believe it is best to work through the Compass issues. If you need help fixing Compass please let me know.

I believe that the error you are getting has to do with the order you are compiling in. It is looking for the transition mixin in the `mixins.scss` file but that hasn't been processed so it doesn't exist. I hope this helps.

A word of note. Not having normalize may change some of the styling of the site because this was built using that as a base. You might want to download a copy of normalize.scss and manually insert it instead of importing it.
